### ISSUE TITLE
Probetrainingshandout Kinder- & Jugendliche aktualisieren

### ISSUE THREAD

**Issue by boeckers** [wingchunforum/Organisation#10]
Wir müssen leider recht dringend das Handout zum Probetraining bei Kindern und Jugendlichen aktualisieren. Verena hat mich leider erst jetzt darauf aufmerksam gemacht: http://wiki.wingchun-forum.de/doku.php?id=orga:kinderhandout
Die Zeiten müssen um die Jugendzeit ergänzt werden und Martin mit in Unterschrift und dem Vorstellungskasten aufgenommen werden.

**Comment by boeckers** [comment]
Ich sehe zu, dass ich den Text heute Abend (Mi) oder morgen (Do) entsprechend ändere. Dann kann der einfach in das PDF-Dokument übernommen werden.

**Comment by boeckers** [comment]
Es muss doch NUR die Uhrzeit geändert werden, denn dieses Handout wird nur für das Kindertraining benutzt. Insofern eigentlich keine große Sache, auf dem WIKI habe ich den Text bereits angepasst.

**Comment by Antimon2000** [comment]
Handout zur Kontrolle soeben an Lars geschickt.

**Comment by boeckers** [comment]
Der letzte Satz in der ersten Spalte " Viermal im Jahr laden wir die Eltern herzlich zu einem gemeinsamen Eltern-Kind-Training ein." muss gestrichen werden, da wir noch nicht wissen, wie wir das Elterntraining zukünftig regeln.

**Comment by boeckers** [comment]
Ausgedruckt und auf dem Wiki eingepflegt. Vielen dank für die schnelle Korrektur.
