### ISSUE TITLE
Pierre als Ausbilder

### ISSUE THREAD

**Issue by boeckers** [wingchunforum/Organisation#11]
Pierre hat such heute prüfen lassen uns ist ab sofort Ausbilder I. Daher muss die E-Mail-Adresse pierre@wingchun-forum.de eingerichtet werden. Zudem muss Foto und Text auf die Website. Pierre weiss Bescheid und sendet demnächst und Text an dich.

**Comment by Antimon2000** [comment]
Hab die E-Mail-Adresse mit einer Weiterleitung auf Pierres privaten E-Mail-Account eingerichtet, da er mich darum gebeten hat.

**Comment by Antimon2000** [comment]
Der Text für die Website fehlt noch. Alles Weitere zu diesem Thema kann in wingchunforum/Website#5 besprochen werden.
