### ISSUE TITLE
thore@wingchunn-forum.de erstellen

### ISSUE THREAD

**Issue by boeckers** [wingchunforum/Organisation#12]
Thore benötigt eine Emailadresse mit Umleitung. Er ist angewiesen, sich diesbezüglich mit dir auseinanderzusetzen.

**Comment by Antimon2000** [comment]
Habe bislang keine Nachricht von ihm erhalten.

**Comment by boeckers** [comment]
Ich sage ihm morgen (22.7.) nochmal Bescheid.

**Comment by boeckers** [comment]
Habe Thore erneut erinnert (20.9.).

**Comment by boeckers** [comment]
Laut Thore liegen dir alle Daten vor.

**Comment by boeckers** [comment]
Ich habe, hoffentlich korrekt, die Adresse eingerichtet und die Weiterleitung aktiviert.
