### ISSUE TITLE
Zugang zu GitHub für Pierre

### ISSUE THREAD

**Issue by boeckers** [wingchunforum/Organisation#13]
Ich würde gerne Pierre einen Zugriff auf unsere GitHub-Seiten ermöglichen, finde aber keine Möglichkeit einen User hinzuzufügen. Liegen die Admin-Rechte bei dir? Könntest du ihn hinzufügen?

**Comment by Antimon2000** [comment]
Nachdem ich endlich die Zugangsdaten wiedergefunden habe, gerne. Wie ist denn sein Username?

**Comment by boeckers** [comment]
Ich denke mal, er hat keinen. Ich hatte nicht daran gedacht, dass er sich zunächst anmelden muss. Ich fordere ihn mal dazu auf. Dann soll er sich bei dir melden.

**Comment by boeckers** [comment]
Der Username von Pierre lautet: PMeinhard.

**Comment by Antimon2000** [comment]
Er ist nun freigeschaltet.
