### ISSUE TITLE
Github verschlüsseln oder privat stellen

### ISSUE THREAD

**Issue by PMeinhard** [wingchunforum/Organisation#16]
Es soll geprüft werden, ob es sinnvoll ist, einen Github-Plan zu kaufen, um private Repositories zu ermöglichen. Habe mich gerade nicht schlecht gewundert als ich nicht eingeloggt unsere Tickets lesen konnte. Gerade geprüft: man findet unsere Repositories auf der ersten Seite bei Google mit den Stichworten "wing chun forum lars böckers"

Umsetzung:
Die Kosten sind hier einzusehen: https://github.com/pricing

Kurzfassung: "Personal Plan Micro", 5 private Repositories, 6.21€/Monat vs. "Organizational Plan Bronze", 10 private Repositories, 22.17€/Monat. 

Steige gerade nicht durch den Unterschied zwischen "Collaborateurs" (Personal Plan) und "Members" (Organizational Plan) durch. Soweit ich es verstehe läuft es auf die Frage raus, ob wir Befugnishierarchien brauchen oder nicht.

**Comment by boeckers** [comment]
Dann sind unsere Tickets in der Tat sehr leicht aufzufinden. Insbesondere wenn wir weitere Respositories zur Redaktion und Werbe-Strategie eröffnen wollen, die auch Interna beinhalten könnten.

Flo, was ist deine Meinung dazu?

**Comment by boeckers** [comment]
Kann jemand erkennen, ob die Preise incl. Umsatzsteuer sind?

**Comment by Antimon2000** [comment]
Ein privates Ticket- und Repositorysystem können wir auch auf unserem eigenen Webspace einrichten. Der Nachteil liegt dann natürlich darin, dass wir es eigenständig warten müssten.

Was ich für wichtiger als einen GitHub-Plan halte, ist allerdings, unser Webhosting auf ein Paket umzustellen, das uns die sog. mod_rewrite-Funktion ermöglicht. Mit der werden unsere Website-URLs für Menschen und vor allem für Suchmaschinen besser lesbar. Wird bei der Platzierung sehr helfen!

**Comment by boeckers** [comment]
Zur Zeit fällt mir nur ein weiteres Respository ein, das wir brauchen könnten, nämlich eines für die Redaktionelle Arbeit. Das könnte Flo dann nicht abonnieren, dann bekäme er nicht unendliche Nachrichten über Dinge, die ihn nicht interessieren. Es würde dann ein Packet mit bis zu fünf Respositorys genügen. Da wir keine Zugriffsrechte für Mitarbeiter vergeben müssen benötigen wir nur einen Personal Plan. Die Kosten wären dann 74€ im Jahr. Der Aufwand ein entsprechendes System auf unserem Webspace einzurichten erscheint mir dagegen unverhältnismäßig hoch.

**Comment by PMeinhard** [comment]
Zumal wir heute besprochen haben, dass ein Repository für die Redaktionsarbeit nur organisatorisch sinnvoll ist und die eigentliche Korrektur- und Editarbeit auf einer anderen Plattform (sinnvolle Lösung demnächst erarbeiten) stattfinden muss.

Kann den Preisen nicht entnehmen ob mit oder ohne Umsatzsteuer.

**Comment by Antimon2000** [comment]
Habe jetzt aber mal kurz recherchiert und bin dabei auf bitbucket.org gestoßen, was einen sehr guten Eindruck macht und was von den selben Entwicklern ist, die auch das professionelle Issue-Tracking-System JIRA entworfen haben, das wir in der Firma benutzen. Mit Bitbucket können wir beliebig viele private Repositorys anlegen, haben ein Wiki und können selbstverständlich auch Code einchecken. Außerdem wird es wie GitHub vom Anbieter selbst gewartet. Die Einschränkung besteht darin, dass die kostenlose Variante nicht mehr als 5 Benutzer zulässt. 10 Nutzer würden dann 10 € pro Monat kosten und 25 Nutzer 25 € pro Monat.

**Comment by boeckers** [comment]
Ich habe es mir mal auf die schnelle angesehen. Nun habe ich wenig Ahnung, aber: wir nutzen die Möglichkeiten, die ein solches System hergibt ja nicht ein mal annährend. Ich wüsste also nicht, warum wir nicht umziehen sollten. Der einzige Einwand könnte der sein, dass wir alle Tickets rüber kopieren müssten. Zur Zeit sind wir ja eh' nur drei Nutzer. Wenn Flo also der Meinung ist, das ist technisch ebenso brauchbar, wäre ich dafür umzuziehen, mir wäre wohler dabei, nicht öffentlich zu schreiben.

**Comment by PMeinhard** [comment]
Befürworte jede preiswerte Lösung, die dazu führt, dass wir nicht mehr öffentlich schreiben.

Szenario 1: Wir werden absehbar mehr als 5 aktive, organisatorisch tätige Benutzer: Dann zahlen wir 26€/Jahr mehr als hier. 

Szenario 2: Wir werden mehr als 10 aktive organisatorische Benutzer: Dann sind wir so groß, dass wir uns ein eigenes System aufsetzen sollten.

Wenn das also vergleichbar gut ist - von mir aus hin da.

**Comment by boeckers** [comment]
Habe gerade gesehen, dass die Respositories von GitHub dort importiert werden können. Insofern wird's einfach.

**Comment by Antimon2000** [comment]
DIe Frage ist: Wie lange wird's dauern bis 6 Personen an den Planungen beteiligt sind? Falls lang genug um x € pro Monat zu sparen, sollten wir umziehen.

Sobald wir dann 6 sind, müssten wir aber u.U. wieder zurückumziehen, wenn's nur um die kosten ginge.

**Comment by boeckers** [comment]
Ok, ich habe dort ein Account unter dem Namen boeckers. Wie funktioniert der Umzug jetzt organisatorisch? Soll ich versuchen die Respositories zu importieren und euch einzuladen, während ihr einen Account anlegt? Oder ist es sinnvoller, das du das machst Flo?

**Comment by Antimon2000** [comment]
Wenn's geht, würd ich's gerne selber machen.

**Comment by boeckers** [comment]
Da wäre ich dir natürlich sehr dankbar für. Und wir sollten daran denken unsere öffentlichen Tickets hier danach zu löschen.

**Comment by Antimon2000** [comment]
Alles klar, ich richte das mal kurz ein!

**Comment by Antimon2000** [comment]
Die Tickets lassen sich nicht per Interface importieren. Um da was zu automatisieren, müsste ich einen gewissen Aufwand treiben. Ob sich das lohnt, weiß ich aber noch nicht. Vielleicht übertragen wir die wichtigen Tickets auch einfach manuell.

**Comment by boeckers** [comment]
Ok, warum nicht? Das Interface macht bei mir den Eindruck, als wäre es genau dafür da? Na ja, mein Vorschlag wäre: du importierst alle Web- und ich alle Organisations-Tickets. Dabei können wir ja aussortieren und/oder nur den aktuellen Stand übertragen.

**Comment by boeckers** [comment]
Musst du evtl. erst die Konten verbinden (Settings/Verbundene Konten) und dort anschließend auf "Import your respositories"?

**Comment by Antimon2000** [comment]
Kann ich natürlich nochmal ausprobieren. Beim Importieren ist aber natürlich zunächst das Repository, also die Codebase, gemeint, nicht die Tickets.

**Comment by boeckers** [comment]
Ach so, ich hatte unterstellt, dass die Tickets mit importiert werden. Dann halt manuell.

**Comment by Antimon2000** [comment]
Bevor du irgendetwas manuell überträgst, lass mich erst versuchen das automatisch zu migrieren. Vielleicht klappt's ja.

**Comment by boeckers** [comment]
Würde ich nicht tun, allein aus Angst dir irgendetwas zu verpfuschen. Ich melde mich erst mal ab, muss mit Katrin grade mal die Kinderbetreuung morgen besprechen. Schaue dann spätestens morgen früh rein. Hoffe, das ist ok.

**Comment by Antimon2000** [comment]
Kein Problem, ich kann gerade eh nicht weitermachen. Versuche, morgen die Tickets zu migrieren. Euch einen schönen Abend!

**Comment by Antimon2000** [comment]
Habe die Tickets nun doch noch migriert. Ab nun bitte nur noch den Issue Tracker unseres Bitbucket-Projekts nutzen: https://bitbucket.org/wingchunforum/

@PMeinhard Sag Bescheid, wenn Du einen Account hast, dann füg ich Dich hinzu
