### ISSUE TITLE
Tag der offenen Tür organisieren

### ISSUE THREAD

**Issue by boeckers** [wingchunforum/Organisation#3]
Am 25. von 14 bis ca. 17 Uhr

**Comment by boeckers** [comment]
Ist im Ultimo, Wochenspiegel, Rundschreiben und auf der Website beworben. Schon allein dadurch wurde über die Website Kontakt zu uns aufgenommen. Selbst wenn sich der TdoT selbst nicht lohnt, so doch die Werbung dafür.

**Comment by boeckers** [comment]
Als Helfer stehen zu Verfügung: Verena, Thore, Lisa, Pierre. Für Auf- und Abbau: Doro, Rufus und Tobias. Ich bitte alle am Samstag etwa eine Stunde vor Beginn zu erscheinen.

**Comment by boeckers** [comment]
Geplant sind: eine kleine Einführung von mir und drei "Stationen": An der ersten kann eine kleine Chi-Sao-Übung ausprobiert werden (Tan-Zyklus) betreut durch Verena. An der Zweiten eine Schlagkraftübung, betreut durch Pierre. An der dritten wird beides zu einer Anwendung zusammengefügt, betreut durch Thore. An der letzten hält Lisa Infos zu Verträgen und Preisen bereit und nimmt Anmeldungen für ein Probetraining entgegen.

**Comment by boeckers** [comment]
Getränke etc. besorge ich am Samstag, Schilder für die Stationen sind gedruckt, für die Aufhängung (Lehrerknete wegen der Tapeten) sorgt Katrin. Anmeldeliste für Probestunden ist gedruckt.

**Comment by boeckers** [comment]
Lehrerknete ist besorgt, alle sind an ihren Stationen eingewiesen, Helfer zum Auf- und Abbau sind organisiert.

**Comment by Antimon2000** [comment]
Wär gut, wenn wir solche Aktionen in Zukunft auch ab „Kampagnenbeginn“ prominent auf der Website bewerben könnten. Wie wir das machen, können wir uns dann überlegen, wenn wir die Website evaluieren. Habe dazu das Ticket wingchunforum/Website#22 angelegt

**Comment by boeckers** [comment]
Ja, bisher habe ich darum so etwas in dem Rundschreiben in der "Einführung" geschrieben, damit das im Aktuelleskasten wenigstens präsent ist.Sicher noch nicht optimal.

**Comment by boeckers** [comment]
Einkäufe gemacht, Personal eingewiesen, morgen dann nur noch die Durchführung. Fazit folgt.

**Comment by boeckers** [comment]
Fazit: 

Nutzen: drei Anmeldungen zum PT durch Telefonate, vor dem Tag der offenen Tür durch die Zeitungspräsenz. Zwei Probetrainingswünsche durch den Tag selbst. Das ist sehr viel, es bleibt abzuwarten, wer tatsächlich kommt. 

Zusätzlicher Nutzen: allgemeine Präsenz in der Zeitung, Verwandte und Partner von Mitgliedern (mögliche Entscheider und Bestimmer) konnten eingebunden werden.

Kosten: Ein Arbeitstag für mindestens fünf Personen, zwei Kuchen und ca. 25 Euro Getränke etc. (diese sind jedoch diesmal kurioserweise durch eine Spende wieder reingekommen. Memo: öfter mal die Kaffeekasse stehen lassen :-)).

 Zusammen mit der Planungszeit, den Textentwürfen für die redaktionellen Texte, Kontakte zu Ultimo und WoSpi ein recht hoher Aufwand für verhältnismäßig wenigen direkten Nutzen. Dieser Aufwand ist bei Beibehaltung des Konzeptes im nächsten Jahr geringer (Texte liegen schon vor etc.)

Die Idee mit den Stationen lässt sich nicht konsequent durchhalten, da doch immer auch eine allgemeinen Ansprache stattfinden muss. Eine Mischung aus beiden hat aber gut geklappt, auch dank der Flexibilität des Teams.
