### ISSUE TITLE
System zur Priorisierung der Tasks

### ISSUE THREAD

**Issue by boeckers** [wingchunforum/Organisation#5]
Evtl. über die Label, z.b. "Dringend", "Prio A",  "Prio B", "Prio C", "Sobald die Vorraussetzungen gegeben"

**Comment by Antimon2000** [comment]
Wir sollten die Priorisierung so einfach wie möglich halten. Habe schon mal die Prio-Labels A–C im Website-Repository angelegt. Das Label "Sobald die Voraussetzungen gegeben" versteh ich aber nicht. Das gilt doch eigentlich immer, oder?

**Comment by boeckers** [comment]
Na ja, es gibt Tasks, bei denen ist es vollkommen egal, welche Priorität wir denen geben, die können nur 'bei Gelegenheit' erledigt werden. Z.B. wenn die Durchführung ausschließlich von jemandem oder einer Gelegenheit abhängt. Z.B. kann ich die Elektrik nicht Priorisieren für unseren Arbeitsprozess, denn Sascha weiß Bescheid, wir können nur warten. Alternativ können wir solche Tasks einfach ohne Prio lassen.

**Comment by boeckers** [comment]
Habe die Prio-Labels auch für die Organisation übernommen. Zudem habe ich die Tasks mal priorisiert. Dabei habe ich alle "technischen" Tasks mal außen vor gelassen, weil du da mehr Ahnung und Durchblick hast, was da wichtig ist.

Du kannst die Prioritäten auch gerne ändern, wenn du anderer Meinung bist, oder dein Arbeitsablauf eine bestimmte Reihenfolge benötigt. So können wir dann evtl. durch Kompromisse eine gemeinsame Priorisierung finden. 

Die Tasks, bei denen wir einfach nur auf eine Gelegenheit lauern müssen, oder dessen Ablauf wir nur überwachen müssen würde ich jetzt einfach ohne Label lassen. 

Damit könnten wir dann diesen Task schließen und nur wieder eröffnen, wenn das System so nicht funktioniert.
