### ISSUE TITLE
Neuer Rahmen für das Bild in der Umkleide der Damen

### ISSUE THREAD

**Issue by boeckers** [wingchunforum/Organisation#8]

**Comment by Antimon2000** [comment]
PRIO A? Sollte A nicht nur der Kram haben, von dem wir erwarten können, dass er spürbar positive Wirkung auf unsere Anmeldezahlen hat?

**Comment by boeckers** [comment]
Haha, ja die Damen laufen uns so alle wieder weg. Nein, sollte eigentlich keine Pro haben. Nein, im Ernst, Github ist super, auch vom Handy, außer für die Dinge, die nur in der Desktopversion möglich sind. Statt Prio A zu entfernen habe ich Prio A im falschen Task gesetzt. Ist aber schon korrigiert.

**Comment by boeckers** [comment]
Erledigt, sieht viel besser aus. Die neuen Mitglieder werden uns die Bude einrennen, besonders die Frauen.

**Comment by Antimon2000** [comment]
Na ein Glück ;-)
