### ISSUE TITLE
Seminaranmeldung entwerfen

### ISSUE THREAD

**Issue by boeckers** [wingchunforum/Organisation#9]
Wir brauchen eine Formatvorlage für Seminaranmeldungen wie Sommerseminar, Dialog im Dunkeln etc. Mündliche zusagen,wie bisher reichen nicht mehr. Durch kurzfristige Absagen ergibt sich zu viel Planungsaufwand. Anmeldungen sollen in Zukunft Ablauf, Zeit, Preis, Stornofrist etc. festhalten. Auch damit den Mitgliedern die Ernsthaftigkeit und Verbindlichkeit der Anmeldung klar wird.

**Comment by Antimon2000** [comment]
Finde ich hervorragend! Mach doch mal einen Entwurf mit allen Informationen, die drauf sollen, und ich mach dir dann die Vorlage.

**Comment by boeckers** [comment]
Ja, mache ich aber dann wohl erst, wenn es aktueller wird. Häufig benötigen wir ja eine schriftliche Anmeldung nicht. Das betrifft ja im Grunde nur die Seminare. Ich überlege, ob wir so etwas für die Kurse auch einführe sollte.

**Comment by boeckers** [comment]
Informationen, die Enthalten sein sollten (Vorschlag):
- Name des Seminars
- Inhalt (Unter-)Titel des Seminars
- (Lern-) Ziel 
- Ausführlich Beschreibung des Ablaufes
- Abgabefrist der Anmeldung
- Kosten
- Stornofrist und Bedingungen

**Comment by boeckers** [comment]
Ich schlage vor wir fertigen das Dokument zweiseitig an. So könnte die Seminarbeschreibung auf die erste Seite und die Anmeldung auf die zweite. Wenn sich jemand Anmelden möchte kann auch nur die zweite Seite ausgedruckt werden. Ich werde ein Probedokument in Word erstellen mit Beispieltexten und dir per Email mal zusenden. Dann kannst du das kommentieren und ggf. ändern. Wenn wir dann eine Endfassung haben können wir daraus eine Vorlage erstellen.

**Comment by boeckers** [comment]
Die Idee ist gut, entpuppt sich aber zunächst als Überflüssig. Die einzigen zwei Seminare, die der schriftlichen Anmeldung bedürfen sind das Sommerseminar und das Training im Dunkeln. Für die benutze ich jedoch spezielle Vorlagen mit entsprechender Seminarbeschreibung.
